# Generated by Django 6.0.2 on 2026-03-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
